version: '2'

networks:
  prodnetwork:
    driver: bridge

services:
 jenkins:
  image: jenkins/jenkins:lts
  ports:
    - "80:8080"
    - "50000:50000"
  networks:
    - prodnetwork
  volumes:
    -  /var/run/docker.sock:/var/run/docker.sock
